"""add_provider_to_agents

Revision ID: a5b19e390259
Revises: 96d7ad5f5a32
Create Date: 2026-05-24 23:42:32.248155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b19e390259'
down_revision: Union[str, Sequence[str], None] = '96d7ad5f5a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('provider', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'provider')
    # ### end Alembic commands ###
